# Generated by Django 3.2.10 on 2022-08-30 11:26

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_jti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='jti',
            field=models.CharField(default=account.utils.generate_jti, editable=False, help_text=('JWT tokens for the user get revoked when JWT id has regenerated.',), max_length=64, verbose_name=('jwt id',)),
        ),
    ]
