# Generated by Django 3.2.10 on 2022-08-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_pricegroup_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricegroup',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
