# Generated by Django 3.2.10 on 2022-08-23 12:09

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_route_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='route',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
