# Generated by Django 3.2.10 on 2022-08-30 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_auto_20220823_1739'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='route',
            managers=[
            ],
        ),
    ]
