# Generated by Django 3.2.10 on 2022-07-27 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('sales_executive', '0001_initial'),
        ('product', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconciliation_type', models.CharField(choices=[('VOID', 'VOID'), ('REFUND', 'REFUND'), ('CREDIT', 'CREDIT')], default='VOID', max_length=200)),
                ('reconciliation_date', models.DateTimeField(max_length=100)),
                ('sales_executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recon_sales_executive', to='sales_executive.salesexecutive')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconciliation_product_type', models.CharField(choices=[('USABLE', 'USABLE'), ('DAMAGE', 'DAMAGE')], max_length=6)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_item_inventory', to='sales_executive.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_item_product', to='product.product')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_reconciliation', to='reconciliation.reconciliation')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_item_transaction', to='transaction.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
