# Generated by Django 3.2.10 on 2022-07-27 09:05

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^(?!0|1|2|3|4|5)[0-9]{10}$', 'Invalid Mobile Number!')])),
                ('wallet', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, validators=[django.core.validators.MaxValueValidator(Decimal('0.00'))])),
                ('is_chain', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_parent', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_address', to='address.address')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.shop')),
                ('price_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_price_group', to='group.pricegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
